export const productsForProducts = [
  {
    _id: {
      testId: '648dfd1ee01e091d8de693a0',
    },
    enabled: true,
    name: 'Test iPad Air',
    sale: true,
    currentPrice: 539,
    previousPrice: 589,
    categories: 'tablet',
    imageUrls: ['ipad/yoydc55qdd3ztm6sempo.jpeg'],
    quantity: 0,
    color: 'Purple',
    brand: 'Apple',
    storage: '64gb',
    itemNo: 'test81130',
    description: 'Your mobile creative studio.',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:46:41.042Z  ',
    },
    saleImg: 'sales/ez2uswlfbndv4kjc8hxy.jpg  ',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de69397',
    },
    enabled: true,
    name: 'Test iPhone 14',
    sale: false,
    currentPrice: 820,
    previousPrice: 870,
    categories: 'cellphone',
    imageUrls: [
      'phones/sxbhotjntv958ygdcsig.png  ',
      'phones/uyt6w5tind2wc2cttyfl.png  ',
      'phones/lpec4japi1spqbjmue7e.png  ',
    ],
    quantity: 1,
    color: 'Yellow',
    brand: 'Apple',
    storage: '128gb',
    itemNo: '83091',
    description:
      'iPhone 14 is a novelty from Apple, which was presented to us at the autumn presentation of 2022.',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:46:31.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'phones/sh0hhb3nygeeviuvkm5m.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693a7',
    },
    enabled: true,
    name: 'Test MacBook Air',
    sale: false,
    currentPrice: 1202,
    previousPrice: 1300,
    categories: 'laptop',
    imageUrls: [
      'laptop/dqmgoy1qu9zzecx8ygu6.jpg',
      'laptop/xodqfu2q30q2jlpp1poc.jpg',
      'laptop/mvwidmcb7wqyubdfqken.jpg',
      'laptop/zlkszl5kqi2evxsshipo.jpg',
      'laptop/xr8t40vhosr67xio83kn.jpg',
      'laptop/kdzuyojphgncmku1fzqf.jpg',
    ],
    quantity: 10,
    color: 'Starlight',
    brand: 'Apple',
    storage: '256gb',
    itemNo: 'test81172',
    description:
      'Apple MacBook Air M2 (2022) with completely hnology and stylish design.',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:48:47.042Z',
    },
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693bb',
    },
    enabled: true,
    name: 'Test Flash drive',
    sale: true,
    currentPrice: 7,
    previousPrice: 12,
    categories: 'accessories',
    imageUrls: ['accessories/tahtxb5ugkzsamtptmgz.jpg'],
    quantity: 30,
    color: 'White',
    brand: 'Transcend',
    itemNo: 'test76061',
    description: '',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T13:11:47.042Z',
    },
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693b0',
    },
    enabled: true,
    name: 'Test Watch Series',
    sale: true,
    currentPrice: 380,
    previousPrice: 450,
    categories: 'watch',
    imageUrls: [
      'watch/jrdjcivisxz1j74ipyig.jpg',
      'watch/bprz8lkhferkpl1le6ra.jpg',
      'watch/d718qtyeskrtvrajeiyp.jpg',
    ],
    quantity: 9,
    color: 'Midnight',
    brand: 'Apple',
    itemNo: 'test83014',
    description: 'The design of the case ofh the large diagonal',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:59:47.042Z',
    },
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693b3',
    },
    enabled: true,
    name: 'Test AirPods Pro 2',
    sale: false,
    currentPrice: 231,
    previousPrice: 260,
    categories: 'headphones',
    imageUrls: [
      'headphone/qmnxgqndghmgouxxxvvu.jpg',
      'headphone/dklzkmtsbwegqxwhkqri.jpg',
      'headphone/sjcqwnfv0uxdlkklty46.jpg',
      'headphone/u3iq1sms73tzasqoi2yo.jpg',
    ],
    quantity: 28,
    color: 'White',
    brand: 'Apple',
    itemNo: '81913',
    description: 'New AirPods Pro 2 appeared in the world with a new H2 chip.',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T13:02:47.042Z',
    },
  },
  {
    _id: {
      $oid: '648dfd1ee01e091d8de693a0',
    },
    enabled: true,
    name: 'Test iPad Air (2022)',
    sale: true,
    currentPrice: 539,
    previousPrice: 589,
    categories: 'tablet',
    imageUrls: ['ipad/yoydc55qdd3ztm6sempo.jpeg'],
    quantity: 0,
    color: 'Purple',
    brand: 'Apple',
    storage: '64gb',
    itemNo: 'test81130',
    description: 'Your mobile creative studio. The powerful Apple M1 processor',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:46:41.042Z',
    },
    saleImg: 'sales/ez2uswlfbndv4kjc8hxy.jpg',
  },
  {
    _id: {
      $oid: '648dfd1ee01e091d8de69397',
    },
    enabled: true,
    name: 'Test iPhone 14',
    sale: false,
    currentPrice: 820,
    previousPrice: 870,
    categories: 'cellphone',
    imageUrls: [
      'phones/sxbhotjntv958ygdcsig.png',
      'phones/uyt6w5tind2wc2cttyfl.png',
      'phones/lpec4japi1spqbjmue7e.png',
    ],
    quantity: 1,
    color: 'Yellow',
    brand: 'Apple',
    storage: '128gb',
    itemNo: '83091',
    description: 'iPhone 14 is a novelty from.',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:46:31.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'phones/sh0hhb3nygeeviuvkm5m.jpg',
  },
  {
    _id: {
      $oid: '648dfd1ee01e091d8de693b5',
    },
    enabled: true,
    name: 'AirPods with Wireless Charging Case',
    sale: false,
    currentPrice: 180,
    previousPrice: 210,
    categories: 'headphones',
    imageUrls: [
      'headphone/tzwfcmljr2nbyzdzh8dq.jpg',
      'headphone/iucdbuqw1jyf7kineniw.jpg',
    ],
    quantity: 21,
    color: 'White',
    brand: 'Apple',
    storage: '128gb',
    itemNo: '76959',
    description: 'This product is covered by',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T13:04:47.042Z',
    },
  },
  {
    _id: {
      $oid: '648dfd1ee01e091d8de693b6',
    },
    enabled: true,
    name: 'AirPods with Charging Case',
    sale: false,
    currentPrice: 124,
    previousPrice: 135,
    categories: 'headphones',
    imageUrls: [
      'headphone/ohv5wqbbejpdygmxmubp.jpg',
      'headphone/iucdbuqw1jyf7kineniw.jpg',
      'headphone/tilz1ugsfltibwkbdvy8.jpg',
    ],
    quantity: 8,
    color: 'White',
    brand: 'Apple',
    storage: '128gb',
    itemNo: '76973',
    description: 'This product is covered by a 3-month warranty',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T13:05:47.042Z',
    },
  },
  {
    _id: {
      $oid: '648dfd1ee01e091d8de6939f',
    },
    enabled: true,
    name: 'iPad 10.9 (2022)',
    sale: false,
    currentPrice: 480,
    previousPrice: 505,
    categories: 'tablet',
    imageUrls: [
      'ipad/tvdxh7mzqa253crbi4hb.jpg',
      'ipad/ptb7pqfoqpsqexnlegtm.jpg',
      'ipad/c8bjtu3bdczluijryubp.jpg',
    ],
    quantity: 30,
    color: 'Blue',
    brand: 'Apple',
    storage: '64gb',
    itemNo: '82159',
    description: 'Updated design The well-known',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:46:39.042Z',
    },
  },
  {
    _id: {
      $oid: '648dfd1ee01e091d8de6939d',
    },
    enabled: true,
    name: 'iPhone SE 2022',
    sale: false,
    currentPrice: 525,
    previousPrice: 570,
    categories: 'cellphone',
    imageUrls: [
      'phones/cpyvxds0huhu578wsfsm.jpg',
      'phones/emzgolaa2qckiwc4wg8b.jpg',
      'phones/gx8bmxthzfeh27njt5vt.jpg',
      'phones/k4gtajlghmrbszeg0blq.jpg',
    ],
    quantity: 10,
    color: 'Midnight',
    brand: 'Apple',
    storage: '128gb',
    itemNo: '81119',
    description: 'iPhone SE 2022 is an ideological',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:46:37.042Z',
    },
  },
  {
    _id: {
      $oid: '648dfd1ee01e091d8de69399',
    },
    enabled: true,
    name: 'iPhone 14 Pro',
    sale: false,
    currentPrice: 1185,
    previousPrice: 1235,
    categories: 'cellphone',
    imageUrls: [
      'phones/xtijnjpqnonqfrxv9vzo.jpg',
      'phones/jg7s5ukjyv38uqyus1z3.jpg',
      'phones/mwikevxu3miu6i4zjekp.jpg',
      'phones/xnughzxtu8brcnth8ce4.jpg',
    ],
    quantity: 19,
    color: 'Gold',
    brand: 'Apple',
    storage: '256gb',
    itemNo: '82120',
    description: 'Apple iPhone 14 Pro (2022) ',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:46:33.042Z',
    },
  },
];

export const productsForHome = [
  {
    _id: {
      testId: '648dfd1ee01e091d8de69397',
    },
    enabled: true,
    name: 'Test iPhone 14',
    sale: false,
    currentPrice: 820,
    previousPrice: 870,
    categories: 'cellphone',
    imageUrls: [
      'phones/sxbhotjntv958ygdcsig.png  ',
      'phones/uyt6w5tind2wc2cttyfl.png  ',
      'phones/lpec4japi1spqbjmue7e.png  ',
    ],
    quantity: 1,
    color: 'Yellow',
    brand: 'Apple',
    storage: '128gb',
    itemNo: '83091',
    description:
      'iPhone 14 is a novelty from Apple, which was presented to us at the autumn presentation of 2022.',
    guarantee: '3 months',
    date: {
      $date: '2019-10-14T12:46:31.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'phones/sh0hhb3nygeeviuvkm5m.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de69398',
    },
    enabled: true,
    name: 'Test iPhone 14 Plus',
    sale: false,
    currentPrice: 892,
    previousPrice: 942,
    categories: 'cellphone',
    imageUrls: [
      'phones/lstlfnohtmxbkf5hbxpr.jpg',
      'phones/cqhrpl4wspax9adtyodn.jpg',
      'phones/vtufde3hbxv0j6ehd8ls.jpg',
    ],
    quantity: 28,
    color: 'Starlight',
    brand: 'Apple',
    storage: '128gb',
    itemNo: 'test81830',
    description: 'iPhone 14 Plus is a completely new',
    guarantee: '3 months',
    date: {
      testDate: '2019-10-14T12:46:23.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'phones/sqetserbxhcwmf3qmh81.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693b1',
    },
    enabled: true,
    name: 'Test Watch Ultra GPS+LTE 49mm Titanium Case',
    sale: false,
    currentPrice: 880,
    previousPrice: 1000,
    categories: 'watch',
    imageUrls: [
      'watch/s0agudbi6ukntarjkhyz.jpg',
      'watch/uymoyzkbhsn59orfwvu6.jpg',
      'watch/hknwjancifqfkwtzqalg.jpg',
    ],
    quantity: 26,
    color: 'Yellow',
    brand: 'Apple',
    itemNo: 'test81890',
    description: 'A redesigned approach to the production',
    guarantee: '3 months',
    date: {
      testDate: '2019-10-14T13:00:47.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'watch/vfuimawj4zbgve1duw4d.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693a4',
    },
    enabled: true,
    name: 'Test iPad Pro 12.9 M1',
    sale: false,
    currentPrice: 1036,
    previousPrice: 1053,
    categories: 'tablet',
    imageUrls: ['ipad/bztmmdglijvbed99ndbj.jpg'],
    quantity: 6,
    color: 'Silver',
    brand: 'Apple',
    storage: '128gb',
    itemNo: 'test79714',
    description: 'M1 chip. iPad Pro with the M1',
    guarantee: '3 months',
    date: {
      testDate: '2019-10-14T12:46:46.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'ipad/rqffke63zvxrrxbt9zcy.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693a9',
    },
    enabled: true,
    name: 'Test MacBook Pro 16 M1Pro',
    sale: false,
    currentPrice: 1986,
    previousPrice: 20022,
    categories: 'laptop',
    imageUrls: [
      'laptop/u4klyid9kku0pbk892ae.jpg',
      'laptop/vlzcic6svprjgkzm5xxc.jpg',
      'laptop/gvkfkt6xmqxbhlhr1znz.jpg',
      'laptop/txz5vucqxqomxuwhiggx.jpg',
    ],
    quantity: 7,
    color: 'Silver',
    brand: 'Apple',
    storage: '512gb',
    itemNo: 'test80718',
    description: "Apple MacBook Pro 16' 2021 is an",
    guarantee: '3 months',
    date: {
      testDate: '2019-10-14T12:51:47.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'laptop/au16s3wrfxddovbmzhlf.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693ac',
    },
    enabled: true,
    name: 'Test MacBook Pro 16 M2Pro',
    sale: false,
    currentPrice: 2285,
    previousPrice: 2350,
    categories: 'laptop',
    imageUrls: [
      'laptop/p11n1gf9ewkow58idhb3.jpg',
      'laptop/iozw5spsx4oehskul5q6.jpg',
      'laptop/mlfnnxi8ibphcg8geyrk.jpg',
      'laptop/kvfjulhnxuaf2qra1yft.jpg',
    ],
    quantity: 48,
    color: 'Space Gray',
    brand: 'Apple',
    storage: '512gb',
    itemNo: 'test82577',
    description: 'A new level of performance and cooling.',
    guarantee: '3 months',
    date: {
      testDate: '2019-10-14T12:54:47.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'laptop/tei2qy1tdlesl6rjscyh.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693b2',
    },
    enabled: true,
    name: 'Test AirPods 3rd generation with Lightning Charging Case',
    sale: false,
    currentPrice: 181,
    previousPrice: 200,
    categories: 'headphones',
    imageUrls: [
      'headphone/egj1bm6mwsa0imaesroo.jpg',
      'headphone/kcytnfnwrjttjvxcu0zr.jpg',
      'headphone/m8lm5oq0h7bj1pv1luzx.jpg',
      'headphone/cv0ujhkjeibecrqxojzp.jpg',
    ],
    quantity: 26,
    color: 'White',
    brand: 'Apple',
    itemNo: 'test82656',
    description: 'Apple AirPods 3 wireless headphones are headphones',
    guarantee: '3 months',
    date: {
      testDate: '2019-10-14T13:01:47.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'headphone/vlw1uhpqs7ofoiku9wuu.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de6939a',
    },
    enabled: true,
    name: 'Test iPhone 14 Pro Max',
    sale: false,
    currentPrice: 1441,
    previousPrice: 1491,
    categories: 'cellphone',
    imageUrls: [
      'phones/y6moj8n8oghrblrcvncz.jpg',
      'phones/fpuetaiekknpvvcgvqjc.jpg',
      'phones/zybjqctmd2lfnzzigruz.jpg',
      'phones/dnuac9nohy4ezjyyaspa.jpg',
    ],
    quantity: 10,
    color: 'Space Black',
    brand: 'Apple',
    storage: '512gb',
    itemNo: 'test82142',
    description: 'Apple iPhone 14 Pro Max (2022) is',
    guarantee: '3 months',
    date: {
      testDate: '2019-10-14T12:46:34.042Z',
    },
    newArrival: true,
    arrivalPhoto: 'phones/cxl1uk639wyjhbo993wv.jpg',
  },
  {
    _id: {
      testId: '648dfd1ee01e091d8de693ad',
    },
    enabled: true,
    name: 'Test Watch SE GPS 40mm',
    sale: false,
    currentPrice: 255,
    previousPrice: 270,
    categories: 'watch',
    imageUrls: [
      'watch/jbcbry7kqdema1theyas.jpg',
      'watch/ryofzc12xgjrckzkpicg.jpg',
    ],
    quantity: 4,
    color: 'Space Gray',
    brand: 'Apple',
    itemNo: 'test81153',
    description: 'Apple Watch SE is a more affordable',
    guarantee: '3 months',
    date: {
      testDate: '2019-10-14T12:55:47.042Z',
    },
  },
];
